ci: patch isar namespace for Android build

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -7,6 +7,7 @@ on:
 
 jobs:
   build:
+    name: Build APK
     runs-on: ubuntu-latest
 
     steps:
@@ -36,6 +37,19 @@ jobs:
       - name: Install dependencies
         run: flutter pub get
 
+      - name: Patch Isar namespace
+        run: |
+          FILE="$HOME/.pub-cache/hosted/pub.dev/isar_flutter_libs-3.1.0+1/android/build.gradle"
+
+          if [ -f "$FILE" ]; then
+            sed -i '/android {/a\    namespace "dev.isar.isar_flutter_libs"' "$FILE"
+            echo "Isar namespace patched"
+          else
+            echo "Isar build.gradle not found"
+            find $HOME/.pub-cache -name build.gradle | grep isar || true
+            exit 1
+          fi
+
       - name: Create .env file from secrets
         run: |
           echo "MY_CLASSES_URL=${{ secrets.MY_CLASSES_URL }}" >> .env
@@ -43,3 +57,10 @@ jobs:
 
       - name: Build APK
         run: flutter build apk --release --obfuscate --split-debug-info=build/debug_info --split-per-abi
+
+      - name: Upload APK to Release
+        uses: ncipollo/release-action@v1
+        with:
+          artifacts: "build/app/outputs/flutter-apk/app-arm64-v8a-release.apk"
+          tag: v1.0.${{ github.run_number }}
+          token: ${{ secrets.MY_GITHUB_TOKEN }}
